name: REST-Assured CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout your REST-Assured Java project
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Set up Java and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.8.5'

      # ✅ Install Allure CLI
      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # ✅ Build and run tests with Maven
      - name: Run Tests with Maven
        run: mvn clean verify -DbaseURL="http://localhost:3000/" || true

      # ✅ Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o target/allure-report --clean

      # ✅ Upload Allure Report
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AllureReport
          path: target/allure-report
